# Generated by Django 5.0.1 on 2025-03-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
