# Generated by Django 5.0.1 on 2025-04-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='student_no',
            field=models.CharField(max_length=20),
        ),
    ]
