# Generated by Django 5.0.1 on 2025-04-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='department',
            field=models.CharField(choices=[('CS', 'Department of Computer Science'), ('IS', 'Department of Information Systems'), ('DIT', 'Department of Information Technology'), ('NET', 'Department of Networks'), ('RAM', 'Department of Records and Archives Management'), ('LIS', 'Department of Library & Information Science')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
