# Generated by Django 5.0.1 on 2025-04-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='course_unit',
        ),
    ]
