# Generated by Django 5.1.7 on 2025-03-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='course',
            new_name='course_unit',
        ),
    ]
