# Generated by Django 5.1.7 on 2025-03-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_course_issue_course_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Student_no',
            field=models.IntegerField(),
        ),
    ]
