# Generated by Django 5.0.1 on 2025-03-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studentprofile_student_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='regristration_no',
        ),
    ]
