# Generated by Django 5.1.7 on 2025-03-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_issue_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Reg_no',
            field=models.CharField(max_length=20),
        ),
    ]
