# Generated by Django 5.0.1 on 2025-04-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_issue_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='Reg_no',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='Student_no',
        ),
    ]
